Python3 compatibility
Chive/pyrate pull request #10
Opened 2016-10-25 13:19 UTC by boojums

Small fixes for python3 compatibility.

2016-10-25 13:49 UTC, Chive requested changes
Hey there, thanks for your PR. Please have a look at the comment I made, thanks!

2016-10-25 13:49 UTC, Chive commented on pyrate/utils/__init__.py
> +    return dict((k, v) for k, v in dirty_dict.items() if v)
this unfortunately will copy the entire dict into memory in Py2 - could you please add six to the app and use [``six.iteritems``](Hey there, thanks for your PR!) instead? Thanks!

2016-10-25 18:14 UTC, boojums commented
Ok, I think that should do it. I'm not very familiar with py2/3 issues so maybe there's more to it?

2016-10-26 07:23 UTC, Chive approved these changes
Awesome, thank you @boojums

2016-10-26 07:24 UTC, merged